import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { QueryClientProvider } from "@/lib/providers";
import { CommandPalette } from "@/components/command-palette";

const geistSans = localFont({
  src: [
    { path: "../public/fonts/Geist-Thin.woff2", weight: "100", style: "normal" },
    { path: "../public/fonts/Geist-ThinItalic.woff2", weight: "100", style: "italic" },
    { path: "../public/fonts/Geist-ExtraLight.woff2", weight: "200", style: "normal" },
    { path: "../public/fonts/Geist-ExtraLightItalic.woff2", weight: "200", style: "italic" },
    { path: "../public/fonts/Geist-Light.woff2", weight: "300", style: "normal" },
    { path: "../public/fonts/Geist-LightItalic.woff2", weight: "300", style: "italic" },
    { path: "../public/fonts/Geist-Regular.woff2", weight: "400", style: "normal" },
    { path: "../public/fonts/Geist-RegularItalic.woff2", weight: "400", style: "italic" },
    { path: "../public/fonts/Geist-Medium.woff2", weight: "500", style: "normal" },
    { path: "../public/fonts/Geist-MediumItalic.woff2", weight: "500", style: "italic" },
    { path: "../public/fonts/Geist-SemiBold.woff2", weight: "600", style: "normal" },
    { path: "../public/fonts/Geist-SemiBoldItalic.woff2", weight: "600", style: "italic" },
    { path: "../public/fonts/Geist-Bold.woff2", weight: "700", style: "normal" },
    { path: "../public/fonts/Geist-BoldItalic.woff2", weight: "700", style: "italic" },
    { path: "../public/fonts/Geist-ExtraBold.woff2", weight: "800", style: "normal" },
    { path: "../public/fonts/Geist-ExtraBoldItalic.woff2", weight: "800", style: "italic" },
    { path: "../public/fonts/Geist-Black.woff2", weight: "900", style: "normal" },
    { path: "../public/fonts/Geist-BlackItalic.woff2", weight: "900", style: "italic" },
  ],
  variable: "--font-geist-sans",
});

const geistMono = localFont({
  src: [
    { path: "../public/fonts/GeistMono-Thin.woff2", weight: "100", style: "normal" },
    { path: "../public/fonts/GeistMono-ThinItalic.woff2", weight: "100", style: "italic" },
    { path: "../public/fonts/GeistMono-ExtraLight.woff2", weight: "200", style: "normal" },
    { path: "../public/fonts/GeistMono-ExtraLightItalic.woff2", weight: "200", style: "italic" },
    { path: "../public/fonts/GeistMono-Light.woff2", weight: "300", style: "normal" },
    { path: "../public/fonts/GeistMono-LightItalic.woff2", weight: "300", style: "italic" },
    { path: "../public/fonts/GeistMono-Regular.woff2", weight: "400", style: "normal" },
    { path: "../public/fonts/GeistMono-Italic.woff2", weight: "400", style: "italic" },
    { path: "../public/fonts/GeistMono-Medium.woff2", weight: "500", style: "normal" },
    { path: "../public/fonts/GeistMono-MediumItalic.woff2", weight: "500", style: "italic" },
    { path: "../public/fonts/GeistMono-SemiBold.woff2", weight: "600", style: "normal" },
    { path: "../public/fonts/GeistMono-SemiBoldItalic.woff2", weight: "600", style: "italic" },
    { path: "../public/fonts/GeistMono-Bold.woff2", weight: "700", style: "normal" },
    { path: "../public/fonts/GeistMono-BoldItalic.woff2", weight: "700", style: "italic" },
    { path: "../public/fonts/GeistMono-ExtraBold.woff2", weight: "800", style: "normal" },
    { path: "../public/fonts/GeistMono-ExtraBoldItalic.woff2", weight: "800", style: "italic" },
    { path: "../public/fonts/GeistMono-Black.woff2", weight: "900", style: "normal" },
    { path: "../public/fonts/GeistMono-BlackItalic.woff2", weight: "900", style: "italic" },
  ],
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <QueryClientProvider>
          <CommandPalette />
          {children}
        </QueryClientProvider>
      </body>
    </html>
  );
}
